export const HYDERABAD_LOCAL_AREAS = [
  'Abids',
  'Ameerpet',
  'Amberpet',
  'Attapur',
  'B N Reddy Nagar',
  'BN Reddy',
  'Banjara Hills',
  'Bandlaguda',
  'Balanagar',
  'Begumpet',
  'Bowenpally',
  'Chaderghat',
  'Chaitanyapuri',
  'Chandrayangutta',
  'Charminar',
  'Dilsukhnagar',
  'Erragadda',
  'Falaknuma',
  'Film Nagar',
  'Gachibowli',
  'Habsiguda',
  'Himayatnagar',
  'Jubilee Hills',
  'Kachiguda',
  'Khairatabad',
  'Khajaguda',
  'Kompally',
  'Kondapur',
  'Kothaguda',
  'Kukatpally',
  'LB Nagar',
  'Madhapur',
  'Malakpet',
  'Manikonda',
  'Mehdipatnam',
  'Miyapur',
  'Malkajgiri',
  'Moti Nagar',
  'Moisapet',
  'Moosapet',
  'Nallagandla',
  'Nagole',
  'Nampally',
  'Narsingi',
  'Nizampet',
  'Old City',
  'Patancheru',
  'Punjagutta',
  'Rajendra Nagar',
  'Sanath Nagar',
  'Secunderabad',
  'Serilingampally',
  'Shaikpet',
  'Shamshabad',
  'Somajiguda',
  'Sainikpuri',
  'Tarnaka',
  'Tellapur',
  'Trimulgherry',
  'Uppal',
  'Yousufguda',
].sort((first, second) => first.localeCompare(second));